"""Integration test verifying Cloud Logging audit records generated by the Remediator."""

import logging
from typing import Any, Dict
from google.cloud import logging as cloud_logging
import pytest

logger = logging.getLogger(__name__)


class TestCloudLoggingAudit:
    """Verifies that remediation actions produce verifiable audit records in Cloud Logging."""

    def test_remediation_event_logged(
        self,
        logging_client: cloud_logging.Client,
        test_config: Dict[str, Any],
    ):
        """Queries Cloud Logging for remediation records emitted by the Cloud Function."""
        function_name = test_config["function_name"]
        filter_str = (
            f'resource.type="cloud_run_revision" AND '
            f'resource.labels.service_name="{function_name}" AND '
            f'(textPayload:"NON-COMPLIANT" OR textPayload:"Remediating fields" OR textPayload:"Successfully patched")'
        )

        logger.info("Searching Cloud Logging with filter: %s", filter_str)
        entries = list(logging_client.list_entries(filter_=filter_str, max_results=10))

        assert len(entries) > 0, (
            f"Expected at least one remediation log entry in Cloud Logging for service {function_name}, "
            f"but found none matching filter: {filter_str}"
        )

        found_sample = entries[0].payload
        logger.info("Found verified remediation log entry in Cloud Logging: %s", found_sample)
        assert "Remediating fields" in str(found_sample) or "NON-COMPLIANT" in str(found_sample)
